// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQIPEG9c7FCyJYu7w1QUjJPDzCYbFV_k',
    appId: '1:178907233965:android:0f3d97e9918ca422a75024',
    messagingSenderId: '178907233965',
    projectId: 'yandex-flutter-task',
    storageBucket: 'yandex-flutter-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJB4brtTxerUdgWUi5xuaSup64Vy5EkcQ',
    appId: '1:178907233965:ios:f64d777947250852a75024',
    messagingSenderId: '178907233965',
    projectId: 'yandex-flutter-task',
    storageBucket: 'yandex-flutter-task.appspot.com',
    iosClientId: '178907233965-vvensd7gv65mki5ulnpl4td4h338rask.apps.googleusercontent.com',
    iosBundleId: 'com.example.yandexFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJB4brtTxerUdgWUi5xuaSup64Vy5EkcQ',
    appId: '1:178907233965:ios:8ed249ba06ba0b37a75024',
    messagingSenderId: '178907233965',
    projectId: 'yandex-flutter-task',
    storageBucket: 'yandex-flutter-task.appspot.com',
    iosClientId: '178907233965-r5agadfej3klsbf8td7in2v1dn71b5fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
